name: Test Docker Builds

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Descargar mi código"
        uses: actions/checkout@v4
        
      - name: "Descargar node js en la maquina de github"
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: "Instalar dependencias del Cliente"
        working-directory: ./client
        run: npm install
      - name: "Lint del Cliente"
        working-directory: ./client
        run: npm run lint
        
      - name: "Construir mi aplicacion (Cliente)"
        working-directory: ./client
        run: npm run build

        
