name: Test Docker Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ["22"]
    runs-on: ubuntu-latest

    steps:
      - name: "Descargar mi código"
        uses: actions/checkout@v4

      - name: "Descargar node js en la maquina de github"
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: "Instalar dependencias del Cliente"
        working-directory: ./client
        run: npm install

      - name: "Lint del Cliente"
        working-directory: ./client
        run: npm run lint

      - name: "Construir mi aplicacion (Cliente)"
        working-directory: ./client
        run: npm run build

      - name: "Ejecutar pruebas del Cliente"
        working-directory: ./client
        run: npm run test

      - name: "Login en Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Construir imagen del Cliente"
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aprendiendo_docker-client:latest ./client
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aprendiendo_docker-client:latest

      - name: "Construir imagen del Servidor"
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aprendiendo_docker-server:latest ./server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aprendiendo_docker-server:latest

      - name: "Desplegar en EC2 por SSH"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Actualizar Cliente
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/aprendiendo_docker-client:latest
            docker stop mi-cliente || true
            docker rm mi-cliente || true
            docker run -d -p 80:3000 --name mi-cliente ${{ secrets.DOCKERHUB_USERNAME }}/aprendiendo_docker-client:latest
