name: Test Docker Builds

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Descargar mi código"
        uses: actions/checkout@v4
      - name: "holaMundo"
        run: echo "hola mundo"
      - name: "dime la fecha"
        run: date
      - name: "muestre el contenido de la carpeta"
        run: ls -la
